# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_thing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='price',
            field=models.IntegerField(),
        ),
    ]
